### PR TITLE
Replace WindiCSS with Tailwind

### PR DESCRIPTION
**Pull request by estebancastro**
The idea is have a dedicated branch to **Tailwind**, like `feature-tailwind` or just `tailwind`. **WindiCSS** can stay on the `main` branch as it currently is, nothing change. Of that way users can use plain **Tailwind** or use **WindiCSS**, make sense?

### CODE REVIEW

**Comment by smonist** [comment]
i will think about this. generally i think it is a good idea to give user options to choose from. since tailwind and windi are very similar and sometimes interchangeable i am not sure what the added benefit of a tailwind option would be. feel free to elaborate if i am missing a point here.

**Comment by smonist** [comment]
will add your "@" resolve to the main branch.

**Comment by estebancastro** [comment]
yeah I understand you, 

remove windi and add tailwind is not hard but there's many steps, something like:

```ddev yarn remove windicss sass```
```rm windi.config.ts```
```ddev yarn add --dev tailwindcss postcss autoprefixer```
```npx tailwindcss init```

delete **sass** files and create **main.css** and add: 
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
add to **app.ts**:  ```import '@/css/main.css';```

add ```postcss.config.js```

also modify the ```vite.config.ts``` 

and if I don't forget any other step, that is! but overall **my point is**: it will be easier just run from the **tailwind** branch and avoid all those steps on each project installation due is a little tedious.

**Comment by smonist** [comment]
hi Esteban,

sorry for my late reply. i am looking towards integrating tailwind instead of windi [as it is sunsetting ](https://windicss.org/posts/sunsetting.html). i will use your PR as a base for this task :)

when the work is done there will be a new release. looking forward to it!

**Comment by smonist** [comment]
After putting way too much effort in trying to get [UnoCSS](https://unocss.dev/) to work, I have put my work there on pause. I wanted to use UnoCSS because it offers very diverse configuration options and does not lock you into a specific CSS framework.

For now, I have created a branch based on your work with updated tailwind dependencies etc. Please take a look at it and tell me what you think of it :)

[tailwind feature branch](https://github.com/szenario-fordesigners/craft-vite-starter/tree/feature-tailwind)

**Comment by estebancastro** [comment]
> After putting way too much effort in trying to get [UnoCSS](https://unocss.dev/) to work, I have put my work there on pause. I wanted to use UnoCSS because it offers very diverse configuration options and does not lock you into a specific CSS framework.
> 
> For now, I have created a branch based on your work with updated tailwind dependencies etc. Please take a look at it and tell me what you think of it :)
> 
> [tailwind feature branch](https://github.com/szenario-fordesigners/craft-vite-starter/tree/feature-tailwind)

Thank you, looks good but how can run from the **feature-tailwind** branch, something like this `ddev composer create -y szenario-fordesigners/craft-vite-starter:feature-tailwind` won't work.

**Comment by smonist** [comment]
I think I need to add an additional branch to the packagist repo. Will look into that tomorrow :)

**Comment by smonist** [comment]
The correct command is `ddev composer create -y szenario-fordesigners/craft-vite-starter:dev-feature-tailwind`. Since this is just a feature branch with no releases (yet), [packagist appended 'dev-'](https://packagist.org/packages/szenario-fordesigners/craft-vite-starter#dev-feature-tailwind) to the branch name. DDEV is using a [slightly different syntax](https://ddev.readthedocs.io/en/stable/users/usage/developer-tools/#ddev-and-composer) than composer, which caused a bit of confusion on my side.

I updated the readme and init script in the `feature-tailwind` branch. When you find the time, please confirm that this also works on MacOS. Have a great weekend 👋

**Comment by estebancastro** [comment]
> The correct command is `ddev composer create -y szenario-fordesigners/craft-vite-starter:dev-feature-tailwind`. Since this is just a feature branch with no releases (yet), [packagist appended 'dev-'](https://packagist.org/packages/szenario-fordesigners/craft-vite-starter#dev-feature-tailwind) to the branch name. DDEV is using a [slightly different syntax](https://ddev.readthedocs.io/en/stable/users/usage/developer-tools/#ddev-and-composer) than composer, which caused a bit of confusion on my side.
> 
> I updated the readme and init script in the `feature-tailwind` branch. When you find the time, please confirm that this also works on MacOS. Have a great weekend 👋

Tested! works fine 🎉 thank you!

**Pull request closed without merging**
