### PR TITLE
feat: add vite favicons

### PR DESCRIPTION
**Pull request by estebancastro**
I know, the idea of this project is provide the essential craft and base vite plugins. This handy plugin could be part of the base? https://github.com/khalwat/vite-plugin-favicon it solve this 404 https://i.redd.it/d492h76eud471.png the plugin easily generating favicons from just one image /src/img/favicon-src.png

### CODE REVIEW

**Comment by smonist** [comment]
Hey! Thank you for the contribution. I will take a look at over it the next days :)

**Comment by smonist** [comment]
I guess we put this one on pause until [https://github.com/khalwat/vite-plugin-favicon/issues/2](https://github.com/khalwat/vite-plugin-favicon/issues/2) is resolved right?

Alternatively, we could take a look at [https://github.com/JohnPremKumar/vite-plugin-favicons-inject](https://github.com/JohnPremKumar/vite-plugin-favicons-inject) instead.

**Comment by estebancastro** [comment]
> I guess we put this one on pause until [khalwat/vite-plugin-favicon#2](https://github.com/khalwat/vite-plugin-favicon/issues/2) is resolved right?
> 
> Alternatively, we could take a look at https://github.com/JohnPremKumar/vite-plugin-favicons-inject instead.

yes, please leave it on pause, I still have that issue https://t.ly/M1U6k I think is related with https://github.com/lovell/sharp and Apple Silicon or node latest versions? I don't know to be honest.

I haven't try the other repo but Andrew plugin https://github.com/khalwat/vite-plugin-favicon/issues/2 seems to have more features and support.

**Comment by estebancastro** [comment]
Just for the record, it works now: https://github.com/khalwat/vite-plugin-favicon/issues/2#issuecomment-1939382157

**Pull request closed without merging**
